name: Main Taski workflow

on:
  push:
    branches:
      - main

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      # Копируем код проекта
      - name: Check out code
        uses: actions/checkout@v3

      # Устанавливаем Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12

      # Обновляем pip, setuptools и wheel через python -m ensurepip
      - name: Ensure pip and setuptools
        run: |
          python -m ensurepip --upgrade
          python -m pip install --upgrade pip setuptools wheel

      # Устанавливаем flake8 и flake8-isort
      - name: Install flake8 and plugins
        run: pip install flake8 flake8-isort

      # Запускаем flake8
      - name: Run flake8
        run: python -m flake8 backend/
